### ISSUE TITLE
Mashes POD and DATA in modules with special literal DATA

### ISSUE THREAD

**Issue by iamalnewkirk** [yanick/Dist-Zilla-Plugin-CoalescePod#4]
Should be:
```
$file->content( join "\n", @content );
```

Maybe even:
```
$file->content( join "\n\n", @content );
```

Currently, this code:
https://github.com/yanick/Dist-Zilla-Plugin-CoalescePod/blob/6f650c091dd94564697dd3e625f82dd595ac4b81/lib/Dist/Zilla/Plugin/CoalescePod.pm#L29

Results in:
```
=pod
=cut__DATA__
```

**Comment by yanick** [comment]
Good catch! Fixing as we speak.

**Comment by yanick** [comment]
Pushed!

**Comment by iamalnewkirk** [comment]
Btw, thanks for the great work. I use this plugin often!
