### ISSUE TITLE
Removes .pod files outside of lib

### ISSUE THREAD

**Issue by awncorp** [yanick/Dist-Zilla-Plugin-CoalescePod#5]
I assumed this plugin would only remove .pod files that it actually matched and merged. It actually indiscriminately removes all files ending in `.pod`.

https://github.com/yanick/Dist-Zilla-Plugin-CoalescePod/blob/c7d7121a159d2bd960dabf07dd00f1ca3b449a2b/lib/Dist/Zilla/Plugin/CoalescePod.pm#L50-L57

**Comment by yanick** [comment]
Hmmm... It's been a while since I wrote that. Lemme check. :-)

**Comment by yanick** [comment]
Aaaand a fixed version should wait for you in CPAN. :-)
